# Generated by Django 3.0.3 on 2020-03-09 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('FOLLOWING', 'FOLLOWING'), ('FRIENDS', 'FRIENDS')], max_length=9)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_author', to=settings.AUTH_USER_MODEL)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['current', 'connection_type'], name='friend_conn_current_9efbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['other', 'connection_type'], name='friend_conn_other_i_77d9ab_idx'),
        ),
    ]
