# Generated by Django 3.0.3 on 2020-03-09 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0002_auto_20200309_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='other',
        ),
        migrations.AddField(
            model_name='friend',
            name='other',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
