# Generated by Django 3.0.3 on 2020-02-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='cc16f84fe25948048f5c7b5c45f8325d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/cc16f84fe25948048f5c7b5c45f8325d', editable=False, max_length=70),
        ),
    ]
