# Generated by Django 3.0.3 on 2020-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(editable=False, max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
