# Generated by Django 3.0.3 on 2020-02-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='d0ce666d2bba420e9d57ad77367a031e', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/d0ce666d2bba420e9d57ad77367a031e', editable=False, max_length=70),
        ),
    ]
