# Generated by Django 3.0.3 on 2020-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200223_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='423038bb0bc1422493f28c631cfb0c51', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/423038bb0bc1422493f28c631cfb0c51', editable=False, max_length=70),
        ),
    ]
