# Generated by Django 3.0.3 on 2020-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200308_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
