# Generated by Django 3.0.3 on 2020-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200223_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='4b932467175e4f7e92f3bbfb9c64f77b', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/4b932467175e4f7e92f3bbfb9c64f77b', editable=False, max_length=70),
        ),
    ]
