# Generated by Django 3.0.3 on 2020-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200303_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='611b7e8f9d794a9dba30cf2cb3120957', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/611b7e8f9d794a9dba30cf2cb3120957', editable=False, max_length=70),
        ),
    ]
