# Generated by Django 3.0.3 on 2020-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200309_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_node',
            field=models.BooleanField(default=False),
        ),
    ]
