# Generated by Django 3.0.3 on 2020-03-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20200303_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='2a0d8a2dee694ca2b45cfa49d7419f8d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/2a0d8a2dee694ca2b45cfa49d7419f8d', editable=False, max_length=70),
        ),
    ]
