# Generated by Django 3.0.3 on 2020-03-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_is_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_node',
        ),
    ]
