# Generated by Django 3.0.3 on 2020-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_remove_author_is_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_node',
            field=models.BooleanField(default=False),
        ),
    ]
