# Generated by Django 3.0.3 on 2020-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_auto_20200303_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='b0a65cee33924cc5836640b88a1268c6', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/b0a65cee33924cc5836640b88a1268c6', editable=False, max_length=70),
        ),
    ]
