# Generated by Django 3.0.3 on 2020-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_author_is_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
