# Generated by Django 3.0.3 on 2020-03-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_auto_20200303_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='8d4bba98fc274c1dbcf2df48c3c197d7', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/8d4bba98fc274c1dbcf2df48c3c197d7', editable=False, max_length=70),
        ),
    ]
