# Generated by Django 3.0.3 on 2020-03-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_auto_20200322_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
