# Generated by Django 3.0.3 on 2020-03-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_auto_20200303_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='3423f1df58a847869c8a42b68ad70cca', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/3423f1df58a847869c8a42b68ad70cca', editable=False, max_length=70),
        ),
    ]
