# Generated by Django 3.0.3 on 2020-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_auto_20200303_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='4826c5e2dadb4e71bc1d7e183f4eefb1', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/4826c5e2dadb4e71bc1d7e183f4eefb1', editable=False, max_length=70),
        ),
    ]
