# Generated by Django 3.0.3 on 2020-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_auto_20200322_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
