# Generated by Django 3.0.3 on 2020-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0011_auto_20200303_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='036c3da3b00c4188b16f70f2a2f61c82', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/036c3da3b00c4188b16f70f2a2f61c82', editable=False, max_length=70),
        ),
    ]
