# Generated by Django 3.0.3 on 2020-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_auto_20200303_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='71f045e53eb047409f091d00fb7ee92f', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/71f045e53eb047409f091d00fb7ee92f', editable=False, max_length=70),
        ),
    ]
