# Generated by Django 3.0.3 on 2020-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_auto_20200304_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='4f2a884e170245349f259e0fe37c61c2', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/4f2a884e170245349f259e0fe37c61c2', editable=False, max_length=70),
        ),
    ]
