# Generated by Django 3.0.3 on 2020-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_auto_20200304_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='361251fa6a65428faed421f42e4403b4', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/361251fa6a65428faed421f42e4403b4', editable=False, max_length=70),
        ),
    ]
