# Generated by Django 3.0.3 on 2020-03-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0015_auto_20200304_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='208f2c0d5cfd4fa4a8cf388cc7fec549', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/208f2c0d5cfd4fa4a8cf388cc7fec549', editable=False, max_length=70),
        ),
    ]
