# Generated by Django 3.0.3 on 2020-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_auto_20200304_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='fe68555457e34fa6ac526eb5d00ebb26', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/fe68555457e34fa6ac526eb5d00ebb26', editable=False, max_length=70),
        ),
    ]
