# Generated by Django 3.0.3 on 2020-03-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0017_auto_20200304_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='d24746563bdb423aa50f2a0cf716ee31', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/d24746563bdb423aa50f2a0cf716ee31', editable=False, max_length=70),
        ),
    ]
