# Generated by Django 3.0.3 on 2020-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0018_auto_20200305_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='8068ee28deb24ad1a004079f06b17e69', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/8068ee28deb24ad1a004079f06b17e69', editable=False, max_length=70),
        ),
    ]
