# Generated by Django 3.0.3 on 2020-03-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0019_auto_20200305_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='b28a01b507144912b81398e365672640', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/b28a01b507144912b81398e365672640', editable=False, max_length=70),
        ),
    ]
