# Generated by Django 3.0.3 on 2020-03-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0020_auto_20200306_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='eeb748d7b68d43c6b72308312299bf74', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/eeb748d7b68d43c6b72308312299bf74', editable=False, max_length=70),
        ),
    ]
