# Generated by Django 3.0.3 on 2020-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0022_auto_20200307_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='657a790b6f12458daef2044ce7638fa9', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/657a790b6f12458daef2044ce7638fa9', editable=False, max_length=70),
        ),
    ]
