# Generated by Django 3.0.3 on 2020-03-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0023_auto_20200307_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='4b03a0ecb74c4b6ab298d5526a19ab7d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/4b03a0ecb74c4b6ab298d5526a19ab7d', editable=False, max_length=70),
        ),
    ]
