# Generated by Django 3.0.3 on 2020-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0024_auto_20200307_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='ce9d87546c1042f7af38cc030adc03a4', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://dsnfof.herokuapp.com/author/ce9d87546c1042f7af38cc030adc03a4', editable=False, max_length=70),
        ),
    ]
