# Generated by Django 3.0.3 on 2020-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='5ddffb976e2d46e5acbdb905e82460b3', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
