# Generated by Django 3.0.3 on 2020-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200303_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='d1accdc8c13c4f2e901ff9205f57bf1e', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
