# Generated by Django 3.0.3 on 2020-03-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200303_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='7591fe019b234c9bab3499272d073401', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
