# Generated by Django 3.0.3 on 2020-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200303_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='22d4d15e0af74285bcfe3818ff580d0e', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
