# Generated by Django 3.0.3 on 2020-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200303_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='12c6e56eff1243b3a88598741732bbc4', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
