# Generated by Django 3.0.3 on 2020-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200303_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='1f0d45373d1d45cbb955c5b219d279ab', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
