# Generated by Django 3.0.3 on 2020-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200304_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='e6154bd08bd94220a0715f3f63e325df', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8ac176d9672146f8b27df7494c80da06', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
