# Generated by Django 3.0.3 on 2020-03-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200304_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='3b570e5aefbb4c3994acc46493147338', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='960bc8aca1454b22badfb8727a28858f', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
