# Generated by Django 3.0.3 on 2020-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200304_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='134c81b7ef4742b2bc5a6f8a3b7de75d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='32c828aaaab8473fa8d93130f4ef6128', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
