# Generated by Django 3.0.3 on 2020-03-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200306_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
    ]
