# Generated by Django 3.0.3 on 2020-03-20 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.AddField(
            model_name='node',
            name='auth_user',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='hostname',
            field=models.URLField(default='hsotname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='server_password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='server_username',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
    ]
