# Generated by Django 3.0.3 on 2020-03-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20200323_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='api_url',
            field=models.URLField(help_text='http://dsnfof.herokuapp.com/api/'),
        ),
        migrations.AlterField(
            model_name='node',
            name='hostname',
            field=models.URLField(help_text='Ex: http://dsnfof.herokuapp.com/'),
        ),
    ]
