# Generated by Django 3.0.3 on 2020-03-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20200323_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='api_url',
            field=models.URLField(help_text='Ex: http://dsnfof.herokuapp.com/api/'),
        ),
    ]
